import type { RoomType } from '@/lib/vision/types';

/**
 * The script the app reads out loud during a walkthrough.
 *
 * Sampling a video on a timer produces whatever the camera happened to be
 * pointed at — mostly hallways and ceilings, because that is what you film
 * while walking. The frames that decide a price are the ones nobody films
 * without being asked: inside the microwave, behind the toilet, the grout in
 * the shower, the floor under the cabinets. A cleaner knows to look there. A
 * homeowner recording their own kitchen does not.
 *
 * So the app asks. One instruction, one frame, next instruction. That buys
 * three things at once:
 *
 *   1. Better evidence. Every frame is aimed at something that carries time.
 *   2. Far less data. Twenty deliberate frames beat two minutes of video, and
 *      the request stays inside the size limit by construction rather than by
 *      luck.
 *   3. A caption per frame. The model is told "this is the kitchen sink"
 *      instead of inferring it, which is where double-counted rooms come from.
 *
 * The list is fixed rather than generated by a model between steps. A model in
 * the loop would add a round trip and a failure mode to every single step, in
 * a stranger's kitchen, on a phone with one bar. The questions worth asking
 * about a kitchen do not change from house to house; what varies is the
 * answer, and the answer is the photograph.
 */

export interface StepTemplate {
  /** Short label shown on screen and used as the frame's caption. */
  title: string;
  /** Read aloud. Written as an instruction to a person holding a phone. */
  spoken: string;
  /**
   * Skippable with "no tengo".
   *
   * Not every home has an oven, and being unable to move past a question about
   * one is how a walkthrough gets abandoned halfway.
   */
  optional?: boolean;
}

export interface SpaceTemplate {
  key: string;
  roomType: RoomType;
  /** Spanish, because the person holding the phone is reading this. */
  label: string;
  emoji: string;
  steps: StepTemplate[];
}

export const SPACE_TEMPLATES: SpaceTemplate[] = [
  {
    key: 'kitchen',
    roomType: 'kitchen',
    label: 'Cocina',
    emoji: '🍳',
    steps: [
      { title: 'Vista general', spoken: 'Ponte en la puerta y apunta a toda la cocina.' },
      { title: 'Encimeras', spoken: 'Ahora enfoca las encimeras y todo lo que haya encima.' },
      { title: 'Fregadero', spoken: 'Apunta al fregadero por dentro, con el grifo.' },
      { title: 'Estufa y hornillas', spoken: 'Enfoca la estufa y las hornillas de cerca.' },
      { title: 'Dentro del microondas', spoken: 'Abre el microondas y apunta adentro.', optional: true },
      { title: 'Dentro del horno', spoken: 'Ahora abre el horno y apunta adentro.', optional: true },
      { title: 'Nevera por fuera', spoken: 'Apunta a la nevera por fuera, sobre todo las manijas.', optional: true },
      { title: 'Suelo', spoken: 'Baja el teléfono y enfoca el suelo, sobre todo debajo de los muebles.' },
      { title: 'Zona de basura', spoken: 'Por último, apunta a donde está la basura.', optional: true },
    ],
  },
  {
    key: 'bathroom',
    roomType: 'bathroom',
    label: 'Baño',
    emoji: '🚿',
    steps: [
      { title: 'Vista general', spoken: 'Desde la puerta, apunta a todo el baño.' },
      { title: 'Inodoro', spoken: 'Enfoca el inodoro de cerca, por dentro y por detrás.' },
      { title: 'Ducha o bañera', spoken: 'Ahora la ducha. Acércate a las juntas de los azulejos.' },
      { title: 'Lavamanos y espejo', spoken: 'Apunta al lavamanos y al espejo.' },
      { title: 'Suelo', spoken: 'Enfoca el suelo y las esquinas.' },
    ],
  },
  {
    key: 'bedroom',
    roomType: 'bedroom',
    label: 'Habitación',
    emoji: '🛏️',
    steps: [
      { title: 'Vista general', spoken: 'Desde la puerta, apunta a toda la habitación.' },
      { title: 'Cama', spoken: 'Enfoca la cama y la ropa de cama.' },
      { title: 'Suelo', spoken: 'Apunta al suelo, incluyendo debajo de la cama si puedes.' },
      { title: 'Superficies y ventanas', spoken: 'Enfoca las mesitas, la cómoda y las ventanas.', optional: true },
    ],
  },
  {
    key: 'living_room',
    roomType: 'living_room',
    label: 'Sala',
    emoji: '🛋️',
    steps: [
      { title: 'Vista general', spoken: 'Apunta a toda la sala desde una esquina.' },
      { title: 'Sofá y sillones', spoken: 'Enfoca el sofá de cerca, incluyendo los cojines.' },
      { title: 'Mesas y superficies', spoken: 'Apunta a las mesas y a lo que haya encima.' },
      { title: 'Suelo o alfombra', spoken: 'Enfoca el suelo o la alfombra.' },
    ],
  },
  {
    key: 'dining_room',
    roomType: 'dining_room',
    label: 'Comedor',
    emoji: '🍽️',
    steps: [
      { title: 'Vista general', spoken: 'Apunta a todo el comedor.' },
      { title: 'Mesa y sillas', spoken: 'Enfoca la mesa y las sillas de cerca.' },
      { title: 'Suelo', spoken: 'Apunta al suelo, sobre todo debajo de la mesa.' },
    ],
  },
  {
    key: 'laundry',
    roomType: 'laundry',
    label: 'Lavadero',
    emoji: '🧺',
    steps: [
      { title: 'Vista general', spoken: 'Apunta a todo el lavadero.' },
      { title: 'Lavadora y secadora', spoken: 'Enfoca la lavadora y la secadora, por fuera y por dentro.' },
      { title: 'Pila o fregadero', spoken: 'Si hay pila, apunta adentro.', optional: true },
      { title: 'Suelo', spoken: 'Enfoca el suelo y detrás de las máquinas.' },
    ],
  },
  {
    key: 'office',
    roomType: 'office',
    label: 'Oficina',
    emoji: '💻',
    steps: [
      { title: 'Vista general', spoken: 'Apunta a toda la oficina.' },
      { title: 'Escritorio', spoken: 'Enfoca el escritorio y lo que haya encima.' },
      { title: 'Suelo', spoken: 'Apunta al suelo y debajo del escritorio.' },
    ],
  },
  {
    key: 'hallway',
    roomType: 'hallway',
    label: 'Pasillo / escaleras',
    emoji: '🚪',
    steps: [
      { title: 'Vista general', spoken: 'Apunta a lo largo del pasillo.' },
      { title: 'Suelo y esquinas', spoken: 'Enfoca el suelo, las esquinas y los rodapiés.' },
    ],
  },
  {
    key: 'other',
    roomType: 'other',
    label: 'Otro espacio',
    emoji: '📦',
    steps: [
      { title: 'Vista general', spoken: 'Apunta a todo el espacio desde la entrada.' },
      { title: 'Lo más sucio', spoken: 'Ahora acércate a la parte que más trabajo va a dar.' },
      { title: 'Suelo', spoken: 'Enfoca el suelo.', optional: true },
    ],
  },
];

export const SPACE_BY_KEY = new Map(SPACE_TEMPLATES.map((s) => [s.key, s]));

/** How many of each space the person picked, e.g. `{ kitchen: 1, bathroom: 2 }`. */
export type SpaceSelection = Record<string, number>;

export interface CaptureStep {
  /** Stable within a plan; used as a React key and for skip bookkeeping. */
  id: string;
  spaceKey: string;
  roomType: RoomType;
  /** "Baño 2" when there is more than one, "Baño" when there is one. */
  spaceLabel: string;
  title: string;
  spoken: string;
  optional: boolean;
}

/**
 * The ceiling on frames in one walkthrough.
 *
 * Bounded by the request size limit, not by the model: the shared encode
 * budget divides 3.8MB across however many frames are planned, so more frames
 * means smaller frames, and past roughly two dozen the images get too soft to
 * judge grout by. That is the real limit, so it is the one written down.
 */
export const MAX_GUIDED_FRAMES = 24;

/** A person can only hold a phone up for so long. Four spaces is already ~3 min. */
export const MAX_SPACES = 8;

export interface CapturePlan {
  steps: CaptureStep[];
  /**
   * Optional steps dropped to fit `MAX_GUIDED_FRAMES`.
   *
   * Surfaced rather than silently applied, because someone who selected a
   * whole house should be told their oven interiors were cut, not left to
   * wonder why the app skipped them.
   */
  droppedOptional: number;
  /** True when even the required steps don't fit — the selection is too big. */
  tooManySpaces: boolean;
}

/**
 * Expands a selection of spaces into the ordered list of instructions.
 *
 * Order matters and is not alphabetical: kitchens and bathrooms carry most of
 * the labour and most of the variance, so they are filmed first. If someone
 * gives up halfway through — which happens — the frames already captured are
 * the ones worth having.
 */
export function buildPlan(selection: SpaceSelection): CapturePlan {
  const ordered = SPACE_TEMPLATES.filter((t) => (selection[t.key] ?? 0) > 0);
  const steps: CaptureStep[] = [];

  for (const template of ordered) {
    const count = Math.min(selection[template.key] ?? 0, MAX_SPACES);
    for (let n = 1; n <= count; n++) {
      const spaceLabel = count > 1 ? `${template.label} ${n}` : template.label;
      const spaceKey = `${template.key}-${n}`;

      for (const [i, step] of template.steps.entries()) {
        steps.push({
          id: `${spaceKey}-${i}`,
          spaceKey,
          roomType: template.roomType,
          spaceLabel,
          title: step.title,
          spoken: step.spoken,
          optional: step.optional ?? false,
        });
      }
    }
  }

  if (steps.length <= MAX_GUIDED_FRAMES) {
    return { steps, droppedOptional: 0, tooManySpaces: false };
  }

  // Trim optional steps from the end first. The spaces filmed last are the
  // ones the estimate depends on least, so their detail shots are the cheapest
  // thing to lose.
  const kept = [...steps];
  let dropped = 0;
  for (let i = kept.length - 1; i >= 0 && kept.length > MAX_GUIDED_FRAMES; i--) {
    if (kept[i].optional) {
      kept.splice(i, 1);
      dropped += 1;
    }
  }

  return {
    steps: kept.slice(0, MAX_GUIDED_FRAMES),
    droppedOptional: dropped,
    tooManySpaces: kept.length > MAX_GUIDED_FRAMES,
  };
}

/** Roughly how long the walkthrough will take, for the "listo?" screen. */
export function estimateWalkSeconds(stepCount: number): number {
  // ~8s per step in testing: hear the instruction, move, aim, shoot.
  return stepCount * 8;
}

/**
 * The caption sent to the model alongside each frame.
 *
 * `spaceKey` is the load-bearing part, not the prose: it is what tells the
 * model that frames 3 and 4 are the same bathroom rather than two of them,
 * which is the single biggest source of wrong room counts. The Spanish title
 * rides along as description; the room type is repeated in English so the
 * model has the vocabulary the rest of the prompt uses.
 */
export function captionFor(step: CaptureStep): string {
  return `[${step.spaceKey}] ${step.roomType} — ${step.title} (${step.spaceLabel})`;
}
