import type { RoomType } from '@/lib/vision/types';

/**
 * The script the app reads out loud during a walkthrough.
 *
 * Sampling a video on a timer produces whatever the camera happened to be
 * pointed at — mostly hallways and ceilings, because that is what you film
 * while walking. The frames that decide a price are the ones nobody films
 * without being asked: inside the microwave, behind the toilet, the grout in
 * the shower, the floor under the cabinets. A cleaner knows to look there. A
 * homeowner recording their own kitchen does not.
 *
 * So the app asks. One instruction, one frame, next instruction. That buys
 * three things at once:
 *
 *   1. Better evidence. Every frame is aimed at something that carries time.
 *   2. Far less data. Twenty deliberate frames beat two minutes of video, and
 *      the request stays inside the size limit by construction rather than by
 *      luck.
 *   3. A caption per frame. The model is told "this is the kitchen sink"
 *      instead of inferring it, which is where double-counted rooms come from.
 *
 * The list is fixed rather than generated by a model between steps. A model in
 * the loop would add a round trip and a failure mode to every single step, in
 * a stranger's kitchen, on a phone with one bar. The questions worth asking
 * about a kitchen do not change from house to house; what varies is the
 * answer, and the answer is the photograph.
 */

/**
 * How a step decides it has what it needs.
 *
 * `settle` waits for the view to change and then hold still — someone aiming
 * at a sink, or swinging a fridge door open and steadying the phone. One frame.
 *
 * `pan` samples across a slow sweep and keeps the most different frames, so an
 * overview of a kitchen covers the room instead of photographing one cupboard
 * three times.
 */
export type StepMode = 'settle' | 'pan';

export interface StepTemplate {
  /** Short label shown on screen and used as the frame's caption. */
  title: string;
  /** Read aloud. Written as an instruction to a person holding a phone. */
  spoken: string;
  /**
   * Said once the shot is taken. Only where the person is left holding
   * something open — nobody should have to guess when they can close the oven.
   */
  after?: string;
  mode?: StepMode;
  /** How many frames a `pan` step keeps. Ignored by `settle`. */
  frames?: number;
  /**
   * Skippable with "no tengo".
   *
   * Not every home has an oven, and being unable to move past a question about
   * one is how a walkthrough gets abandoned halfway.
   */
  optional?: boolean;
}

export interface SpaceTemplate {
  key: string;
  roomType: RoomType;
  /** Spanish, because the person holding the phone is reading this. */
  label: string;
  emoji: string;
  steps: StepTemplate[];
}

/**
 * One of these is not like the others.
 *
 * Every space below is filmed to judge how dirty it is. `closet` is filmed to
 * judge how much STUFF is in it, which is a different question with a
 * different answer — and one no walkthrough can answer unless somebody opens
 * the door.
 *
 * That distinction came from a measured job: a 945 sq ft apartment, clean
 * apart from dust, where 39 of 71 minutes went into reorganising one laundry
 * cupboard. From the room, with the doors shut, that cupboard is a white
 * panel. A tidy one and a disastrous one are the same photograph. No vision
 * model can price the difference — not a hosted one, not a self-hosted
 * detector, not one trained on a million homes — because the information is
 * not in the image.
 *
 * So it is asked rather than inferred, and it is asked the only way that
 * works: by walking someone through opening the door.
 */
export const SPACE_TEMPLATES: SpaceTemplate[] = [
  {
    key: 'kitchen',
    roomType: 'kitchen',
    label: 'Cocina',
    emoji: '🍳',
    steps: [
      {
        title: 'Vista general',
        spoken: 'Ponte en la puerta y haz un paneo lento de la cocina, de izquierda a derecha.',
        mode: 'pan',
        frames: 3,
      },
      { title: 'Encimeras', spoken: 'Ahora enfoca las encimeras y todo lo que haya encima.' },
      { title: 'Fregadero', spoken: 'Apunta al fregadero por dentro, con el grifo.' },
      { title: 'Estufa y hornillas', spoken: 'Enfoca la estufa y las hornillas de cerca.' },
      {
        title: 'Dentro del microondas',
        spoken: 'Abre el microondas y apunta adentro. Sujeta el teléfono quieto un segundo.',
        after: 'Listo, ya puedes cerrarlo.',
        optional: true,
      },
      {
        title: 'Dentro del horno',
        spoken: 'Ahora abre el horno y apunta adentro.',
        after: 'Ya está, ciérralo.',
        optional: true,
      },
      {
        title: 'Dentro de la nevera',
        spoken: 'Abre la nevera y apunta a los estantes.',
        after: 'Perfecto, ciérrala.',
        optional: true,
      },
      { title: 'Suelo', spoken: 'Baja el teléfono y enfoca el suelo, sobre todo debajo de los muebles.' },
      { title: 'Zona de basura', spoken: 'Por último, apunta a donde está la basura.', optional: true },
    ],
  },
  {
    key: 'bathroom',
    roomType: 'bathroom',
    label: 'Baño',
    emoji: '🚿',
    steps: [
      { title: 'Vista general', spoken: 'Desde la puerta, haz un paneo lento de todo el baño.', mode: 'pan', frames: 2 },
      { title: 'Inodoro', spoken: 'Enfoca el inodoro de cerca, por dentro y por detrás.' },
      { title: 'Ducha o bañera', spoken: 'Ahora la ducha. Acércate a las juntas de los azulejos.' },
      { title: 'Lavamanos y espejo', spoken: 'Apunta al lavamanos y al espejo.' },
      { title: 'Suelo', spoken: 'Enfoca el suelo y las esquinas.' },
    ],
  },
  {
    key: 'bedroom',
    roomType: 'bedroom',
    label: 'Habitación',
    emoji: '🛏️',
    steps: [
      { title: 'Vista general', spoken: 'Desde la puerta, haz un paneo lento de toda la habitación.', mode: 'pan', frames: 2 },
      { title: 'Cama', spoken: 'Enfoca la cama y la ropa de cama.' },
      { title: 'Suelo', spoken: 'Apunta al suelo, incluyendo debajo de la cama si puedes.' },
      { title: 'Superficies y ventanas', spoken: 'Enfoca las mesitas, la cómoda y las ventanas.', optional: true },
    ],
  },
  {
    key: 'living_room',
    roomType: 'living_room',
    label: 'Sala',
    emoji: '🛋️',
    steps: [
      { title: 'Vista general', spoken: 'Desde una esquina, haz un paneo lento de toda la sala.', mode: 'pan', frames: 2 },
      { title: 'Sofá y sillones', spoken: 'Enfoca el sofá de cerca, incluyendo los cojines.' },
      { title: 'Mesas y superficies', spoken: 'Apunta a las mesas y a lo que haya encima.' },
      { title: 'Suelo o alfombra', spoken: 'Enfoca el suelo o la alfombra.' },
    ],
  },
  {
    key: 'dining_room',
    roomType: 'dining_room',
    label: 'Comedor',
    emoji: '🍽️',
    steps: [
      { title: 'Vista general', spoken: 'Haz un paneo lento de todo el comedor.', mode: 'pan', frames: 2 },
      { title: 'Mesa y sillas', spoken: 'Enfoca la mesa y las sillas de cerca.' },
      { title: 'Suelo', spoken: 'Apunta al suelo, sobre todo debajo de la mesa.' },
    ],
  },
  {
    key: 'laundry',
    roomType: 'laundry',
    label: 'Lavadero',
    emoji: '🧺',
    steps: [
      { title: 'Vista general', spoken: 'Haz un paneo lento de todo el lavadero.', mode: 'pan', frames: 2 },
      {
        title: 'Lavadora y secadora',
        spoken: 'Abre la lavadora y apunta al tambor por dentro.',
        after: 'Ya puedes cerrarla.',
      },
      { title: 'Pila o fregadero', spoken: 'Si hay pila, apunta adentro.', optional: true },
      { title: 'Suelo', spoken: 'Enfoca el suelo y detrás de las máquinas.' },
    ],
  },
  {
    key: 'office',
    roomType: 'office',
    label: 'Oficina',
    emoji: '💻',
    steps: [
      { title: 'Vista general', spoken: 'Haz un paneo lento de toda la oficina.', mode: 'pan', frames: 2 },
      { title: 'Escritorio', spoken: 'Enfoca el escritorio y lo que haya encima.' },
      { title: 'Suelo', spoken: 'Apunta al suelo y debajo del escritorio.' },
    ],
  },
  {
    key: 'hallway',
    roomType: 'hallway',
    label: 'Pasillo / escaleras',
    emoji: '🚪',
    steps: [
      { title: 'Vista general', spoken: 'Haz un paneo lento a lo largo del pasillo.', mode: 'pan', frames: 2 },
      { title: 'Suelo y esquinas', spoken: 'Enfoca el suelo, las esquinas y los rodapiés.' },
    ],
  },
  {
    key: 'closet',
    roomType: 'other',
    label: 'Armario / despensa (organizar)',
    emoji: '🗄️',
    steps: [
      {
        title: 'Armario cerrado',
        spoken: 'Ponte frente al armario, con las puertas cerradas, y apunta.',
      },
      {
        title: 'Armario abierto',
        spoken: 'Ahora ábrelo del todo y apunta adentro. Sujeta el teléfono quieto.',
        after: 'Déjalo abierto, vamos por los estantes.',
      },
      {
        title: 'Estantes de arriba',
        spoken: 'Enfoca los estantes de arriba, de cerca.',
      },
      {
        title: 'Estantes de abajo',
        spoken: 'Ahora los de abajo y el suelo del armario.',
        after: 'Listo, ya puedes cerrarlo.',
      },
    ],
  },
  {
    key: 'other',
    roomType: 'other',
    label: 'Otro espacio',
    emoji: '📦',
    steps: [
      { title: 'Vista general', spoken: 'Desde la entrada, haz un paneo lento de todo el espacio.', mode: 'pan', frames: 2 },
      { title: 'Lo más sucio', spoken: 'Ahora acércate a la parte que más trabajo va a dar.' },
      { title: 'Suelo', spoken: 'Enfoca el suelo.', optional: true },
    ],
  },
];

export const SPACE_BY_KEY = new Map(SPACE_TEMPLATES.map((s) => [s.key, s]));

/** How many of each space the person picked, e.g. `{ kitchen: 1, bathroom: 2 }`. */
export type SpaceSelection = Record<string, number>;

export interface CaptureStep {
  /** Stable within a plan; used as a React key and for skip bookkeeping. */
  id: string;
  spaceKey: string;
  roomType: RoomType;
  /** "Baño 2" when there is more than one, "Baño" when there is one. */
  spaceLabel: string;
  title: string;
  spoken: string;
  after?: string;
  mode: StepMode;
  /** Frames this step contributes. 1 for `settle`, more for a pan. */
  frames: number;
  optional: boolean;
}

/**
 * The ceiling on frames in one walkthrough.
 *
 * Bounded by the request size limit, not by the model: the shared encode
 * budget divides 3.8MB across however many frames are planned, so more frames
 * means smaller frames, and past roughly two dozen the images get too soft to
 * judge grout by. That is the real limit, so it is the one written down.
 */
export const MAX_GUIDED_FRAMES = 24;

/** A person can only hold a phone up for so long. Four spaces is already ~3 min. */
export const MAX_SPACES = 8;

export interface CapturePlan {
  steps: CaptureStep[];
  /**
   * Optional steps dropped to fit `MAX_GUIDED_FRAMES`.
   *
   * Surfaced rather than silently applied, because someone who selected a
   * whole house should be told their oven interiors were cut, not left to
   * wonder why the app skipped them.
   */
  droppedOptional: number;
  /** True when even the required steps don't fit — the selection is too big. */
  tooManySpaces: boolean;
}

/**
 * Expands a selection of spaces into the ordered list of instructions.
 *
 * Order matters and is not alphabetical: kitchens and bathrooms carry most of
 * the labour and most of the variance, so they are filmed first. If someone
 * gives up halfway through — which happens — the frames already captured are
 * the ones worth having.
 */
export function buildPlan(selection: SpaceSelection): CapturePlan {
  const ordered = SPACE_TEMPLATES.filter((t) => (selection[t.key] ?? 0) > 0);
  const steps: CaptureStep[] = [];

  for (const template of ordered) {
    const count = Math.min(selection[template.key] ?? 0, MAX_SPACES);
    for (let n = 1; n <= count; n++) {
      const spaceLabel = count > 1 ? `${template.label} ${n}` : template.label;
      const spaceKey = `${template.key}-${n}`;

      for (const [i, step] of template.steps.entries()) {
        steps.push({
          id: `${spaceKey}-${i}`,
          spaceKey,
          roomType: template.roomType,
          spaceLabel,
          title: step.title,
          spoken: step.spoken,
          after: step.after,
          mode: step.mode ?? 'settle',
          frames: step.mode === 'pan' ? (step.frames ?? 2) : 1,
          optional: step.optional ?? false,
        });
      }
    }
  }

  // The cap is on frames, not on steps: a pan contributes several, so counting
  // steps would let an eight-room plan sail past the limit it is meant to hold.
  const frameTotal = (list: CaptureStep[]) => list.reduce((sum, s) => sum + s.frames, 0);

  if (frameTotal(steps) <= MAX_GUIDED_FRAMES) {
    return { steps, droppedOptional: 0, tooManySpaces: false };
  }

  // Trim optional steps from the end first. The spaces filmed last are the
  // ones the estimate depends on least, so their detail shots are the cheapest
  // thing to lose.
  const kept = [...steps];
  let dropped = 0;
  for (let i = kept.length - 1; i >= 0 && frameTotal(kept) > MAX_GUIDED_FRAMES; i--) {
    if (kept[i].optional) {
      kept.splice(i, 1);
      dropped += 1;
    }
  }

  // Still over: drop whole steps off the end rather than truncating mid-pan,
  // which would leave a step promising three frames and delivering one.
  while (kept.length > 0 && frameTotal(kept) > MAX_GUIDED_FRAMES) kept.pop();

  return {
    steps: kept,
    droppedOptional: dropped,
    tooManySpaces: frameTotal(steps) > MAX_GUIDED_FRAMES && dropped === 0,
  };
}

/** Total frames a plan will produce, which is what the size budget divides. */
export function planFrameCount(steps: CaptureStep[]): number {
  return steps.reduce((sum, s) => sum + s.frames, 0);
}

/** Roughly how long the walkthrough will take, for the planning screen. */
export function estimateWalkSeconds(steps: CaptureStep[]): number {
  // ~9s per step: hear the instruction, walk to it, aim, hold still. A pan
  // runs longer because the sweep itself has to be slow enough to stay sharp.
  return steps.reduce((sum, s) => sum + (s.mode === 'pan' ? 14 : 9), 0);
}

/**
 * The caption sent to the model alongside each frame.
 *
 * `spaceKey` is the load-bearing part, not the prose: it is what tells the
 * model that frames 3 and 4 are the same bathroom rather than two of them,
 * which is the single biggest source of wrong room counts. The Spanish title
 * rides along as description; the room type is repeated in English so the
 * model has the vocabulary the rest of the prompt uses.
 */
export function captionFor(step: CaptureStep): string {
  return `[${step.spaceKey}] ${step.roomType} — ${step.title} (${step.spaceLabel})`;
}
